/**
 * Union Types Integration Tests
 *
 * Tests for TypeSpec union type generation
 * Sealed interfaces, discriminated unions, union variants
 */

import { describe, it, expect, beforeAll } from "vitest";
import { GoTypeMapper } from "../domain/go-type-mapper.js";
import { StandaloneGoGenerator } from "../standalone-generator.js";
import type { MappedGoType } from "../domain/type-interfaces.js";

describe("Union Types Generation", () => {
  let generator: StandaloneGoGenerator;

  beforeAll(async () => {
    generator = new StandaloneGoGenerator();
  });

  describe("Union Type Detection", () => {
    it("should detect union types correctly", () => {
      // Mock union type matching what mapper expects
      const mockUnionType = {
        kind: "union",
        name: "PetType",
        variants: [
          { type: { kind: "String" } },
          { type: { kind: "Int32" } },
          { type: { kind: "Boolean" } },
        ],
      };

      const result = GoTypeMapper.mapTypeSpecType(mockUnionType, "PetType");

      expect(result.kind).toBe("union");
      expect(result.name).toBe("PetType");
      expect(result.unionVariants).toBeDefined();
      expect(result.unionVariants?.length).toBe(3);
    });

    it("should generate union type strings correctly", () => {
      const unionType: MappedGoType = {
        kind: "union",
        name: "PetType",
        unionVariants: [
          { kind: "struct", name: "Dog", usePointerForOptional: true },
          { kind: "struct", name: "Cat", usePointerForOptional: true },
        ],
        usePointerForOptional: false,
      };

      const result = GoTypeMapper.generateGoTypeString(unionType);
      expect(result).toBe("PetType");
    });

    it("should handle empty unions gracefully", () => {
      const emptyUnionType: MappedGoType = {
        kind: "union",
        name: "EmptyUnion",
        unionVariants: [],
        usePointerForOptional: false,
      };

      const result = GoTypeMapper.generateGoTypeString(emptyUnionType);
      expect(result).toBe("interface{}");
    });
  });

  describe("Union Interface Generation", () => {
    it("should generate sealed interface for union", () => {
      const unionInterface = `// Auto-generated from TypeSpec model: PetType
// Generated by Type-safe Professional Go Emitter
package api

type PetType interface {
  isPetType()
}

// Union implementations
func (Dog) isPetType() {}
func (Cat) isPetType() {}
func (Fish) isPetType() {}
`;

      // Test that the interface contains required elements
      expect(unionInterface).toContain("type PetType interface");
      expect(unionInterface).toContain("isPetType()");
      expect(unionInterface).toContain("func (Dog) isPetType()");
      expect(unionInterface).toContain("func (Cat) isPetType()");
      expect(unionInterface).toContain("func (Fish) isPetType()");
    });

    it("should handle single variant unions", () => {
      const singleVariantUnion = `// Auto-generated from TypeSpec model: StatusType
// Generated by Type-safe Professional Go Emitter
package api

type StatusType interface {
  isStatusType()
}

// Union implementations
func (Active) isStatusType() {}
`;

      expect(singleVariantUnion).toContain("type StatusType interface");
      expect(singleVariantUnion).toContain("func (Active) isStatusType()");
    });
  });

  describe("Discriminated Unions", () => {
    it("should handle discriminated union patterns", () => {
      // This test validates the structure for future discriminated union support
      const discriminatedUnion = {
        kind: "union",
        name: "ApiResponse",
        variants: [
          { type: { kind: "model", name: "Success" } },
          { type: { kind: "model", name: "Error" } },
        ],
      };

      const result = GoTypeMapper.mapTypeSpecType(discriminatedUnion, "ApiResponse");

      expect(result.kind).toBe("union");
      expect(result.name).toBe("ApiResponse");
      expect(result.unionVariants?.length).toBe(2);
    });

    it("should generate proper Go interface names", () => {
      const testCases = [
        { input: "pet_type", expected: "PetType" },
        { input: "api-response", expected: "ApiResponse" },
        { input: "user_role", expected: "UserRole" },
      ];

      testCases.forEach(({ input, expected }) => {
        const mockUnion = {
          kind: "union",
          name: input,
          variants: [{ type: { kind: "model", name: "Test" } }],
        };

        const result = GoTypeMapper.mapTypeSpecType(mockUnion, input);
        expect(result.name).toBe(expected);
      });
    });
  });

  describe("Union Error Handling", () => {
    it("should handle null union variants gracefully", () => {
      const nullVariantsUnion: MappedGoType = {
        kind: "union",
        name: "NullUnion",
        unionVariants: undefined,
        usePointerForOptional: false,
      };

      const result = GoTypeMapper.generateGoTypeString(nullVariantsUnion);
      expect(result).toBe("interface{}");
    });

    it("should handle malformed union variants", () => {
      const malformedUnion: MappedGoType = {
        kind: "union",
        name: "MalformedUnion",
        unionVariants: [
          { kind: "basic", name: "ValidType", usePointerForOptional: false },
          // @ts-expect-error Testing malformed variant
          { kind: "invalid", name: "InvalidType", usePointerForOptional: false },
        ],
        usePointerForOptional: false,
      };

      // Should not throw, should handle gracefully
      expect(() => {
        GoTypeMapper.generateGoTypeString(malformedUnion);
      }).not.toThrow();
    });
  });

  describe("Union Integration with Models", () => {
    it("should handle models containing union properties", () => {
      const modelWithUnion = {
        name: "Pet",
        properties: new Map([
          [
            "name",
            { name: "name", type: { kind: "String" }, optional: false },
          ],
          [
            "age",
            { name: "age", type: { kind: "Uint8" }, optional: true },
          ],
        ]),
      };

      const result = generator.generateModel(modelWithUnion);
      
      // Should generate successfully
      expect(result._tag).toBe("success");
      
      // Should contain proper Go code
      const goCode = Array.from(result.data.values())[0];
      expect(goCode).toContain("Name");
      expect(goCode).toContain("Age");
      expect(goCode).toContain("uint8");
    });
  });

  describe("Performance Tests", () => {
    it("should handle large unions efficiently", () => {
      const startTime = performance.now();
      
      // Create union with many variants
      const largeUnionType: MappedGoType = {
        kind: "union",
        name: "LargeUnion",
        unionVariants: Array.from({ length: 100 }, (_, i) => ({
          kind: "struct",
          name: `Variant${i}`,
          usePointerForOptional: true,
        })),
        usePointerForOptional: false,
      };

      const result = GoTypeMapper.generateGoTypeString(largeUnionType);
      const endTime = performance.now();
      
      // Should complete quickly (under 1ms)
      expect(endTime - startTime).toBeLessThan(1);
      expect(result).toBe("LargeUnion");
    });

    it("should not have memory leaks with union generation", () => {
      const initialMemory = process.memoryUsage().heapUsed;
      
      // Generate many union types
      for (let i = 0; i < 1000; i++) {
        const unionType: MappedGoType = {
          kind: "union",
          name: `Union${i}`,
          unionVariants: [
            { kind: "struct", name: "A", usePointerForOptional: true },
            { kind: "struct", name: "B", usePointerForOptional: true },
          ],
          usePointerForOptional: false,
        };
        
        GoTypeMapper.generateGoTypeString(unionType);
      }
      
      // Force garbage collection if available
      if (global.gc) {
        global.gc();
      }
      
      const finalMemory = process.memoryUsage().heapUsed;
      const memoryIncrease = finalMemory - initialMemory;
      
      // Memory increase should be minimal (less than 10MB)
      expect(memoryIncrease).toBeLessThan(10 * 1024 * 1024);
    });
  });
});