package models

// Auto-generated from TypeSpec model: test-example
// Generated by Type-safe Professional Go Emitter
type Test-example struct {
  Id string `json:"id"`
  Name string `json:"name"`
  ProductName string `json:"productName"`
  LoginCount uint32 `json:"loginCount"`
  ProductID uint32 `json:"productID"`
  Age uint8 `json:"age"`
  Active bool `json:"active"`
  InStock bool `json:"inStock"`
  Score float32 `json:"score"`
  Price float64 `json:"price"`
}
