/**
 * TypeSpec Model to Go Struct Generator
 *
 * Core generator for TypeSpec models to Go structs
 * Domain-driven design with intelligent type mapping
 */

import type { Program } from "@typespec/compiler";
import { BaseGenerator } from "./base-generator.js";
import type { GoEmitterResult } from "../domain/unified-errors.js";
import { ErrorFactory } from "../domain/error-factory.js";
import { GoTypeMapper } from "../domain/go-type-mapper.js";
import { ModelExtractor } from "../emitter/model-extractor.js";

/**
 * TypeSpec Model Generator
 * DOMAIN LOGIC: TypeSpec models to Go structs conversion
 */
export class ModelGenerator extends BaseGenerator {
  readonly name = "model-generator";
  readonly description = "TypeSpec models to Go structs generator";

  async generate(program: Program): Promise<GoEmitterResult> {
    // Input validation
    const validation = this.validateInput(program);
    if (validation) {
      return validation;
    }

    try {
      // Extract models using modular extractor
      const models = ModelExtractor.extractModels(program);
      const allGeneratedFiles = new Map<string, string>();

      // Generate Go struct for each model
      for (const [modelName, extractedModel] of models) {
        const goStruct = this.generateGoStruct(modelName, extractedModel);
        const fileName = this.getFileName(modelName);
        allGeneratedFiles.set(fileName, goStruct);
      }

      // Return successful result
      return ErrorFactory.createSuccess(allGeneratedFiles, {
        generatedFiles: Array.from(allGeneratedFiles.keys()),
      });
    } catch (error) {
      return ErrorFactory.createTypeSpecCompilerError(
        `Model generation failed: ${error instanceof Error ? error.message : String(error)}`,
        {
          resolution: "Check TypeSpec model definitions for syntax errors",
        },
      );
    }
  }

  /**
   * Generate Go struct from extracted model
   * DOMAIN LOGIC: Clean Go struct generation with proper types
   */
  private generateGoStruct(
    modelName: string,
    extractedModel: { name: string; properties: ReadonlyMap<string, any> }
  ): string {
    const imports = new Set<string>();
    const fields: string[] = [];

    // Process each property
    for (const [propertyName, property] of extractedModel.properties) {
      const goType = GoTypeMapper.getTypeSpecType(property.type);
      const jsonTag = this.getJsonTag(propertyName);
      
      // Handle optional types
      if (property.optional) {
        fields.push(`  ${this.capitalize(propertyName)} *${goType} \`${jsonTag}\``);
      } else {
        fields.push(`  ${this.capitalize(propertyName)} ${goType} \`${jsonTag}\``);
      }
    }

    // Generate Go struct with imports
    const goStruct = [
      this.generateHeader(modelName),
      this.generateImports(imports),
      this.generateStructBody(modelName, fields),
      this.generateFooter(),
    ].join('\n');

    return goStruct;
  }

  /**
   * Generate Go file header
   * DOMAIN LOGIC: Professional Go file header
   */
  private generateHeader(modelName: string): string {
    return `// Auto-generated from TypeSpec model: ${modelName}
// Generated by Type-safe Professional Go Emitter
package api

`;
  }

  /**
   * Generate Go imports
   * DOMAIN LOGIC: Clean imports management
   */
  private generateImports(imports: Set<string>): string {
    if (imports.size === 0) {
      return '';
    }

    const importStatements = Array.from(imports)
      .sort()
      .map(imp => `import "${imp}"`);

    return '\n' + importStatements.join('\n') + '\n\n';
  }

  /**
   * Generate Go struct body
   * DOMAIN LOGIC: Clean Go struct generation
   */
  private generateStructBody(modelName: string, fields: string[]): string {
    if (fields.length === 0) {
      return `type ${modelName} struct {}`;
    }

    return `type ${modelName} struct {\n${fields.join('\n')}\n}`;
  }

  /**
   * Generate Go file footer
   * DOMAIN LOGIC: Clean Go file footer
   */
  private generateFooter(): string {
    return '\n';
  }

  /**
   * Get Go file name from model name
   * DOMAIN LOGIC: Proper Go file naming
   */
  private getFileName(modelName: string): string {
    return `${this.capitalize(modelName)}.go`;
  }

  /**
   * Get JSON tag for property
   * DOMAIN LOGIC: Proper JSON tag generation
   */
  private getJsonTag(propertyName: string): string {
    const snakeCase = propertyName
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .toLowerCase();
    
    const tagName = propertyName === snakeCase ? propertyName : snakeCase;
    return `${tagName}${propertyName === 'id' ? ',omitempty' : ',omitempty'}`;
  }

  /**
   * Capitalize first letter (PascalCase)
   * DOMAIN LOGIC: Proper Go naming conventions
   */
  private capitalize(name: string): string {
    return name.charAt(0).toUpperCase() + name.slice(1);
  }
}