/**
 * TypeSpec Model Generator - Utility Module
 *
 * Helper functions and utilities for model generation
 * Clean separation of concerns for generator architecture
 */

import type { ExtractedOperation } from "../emitter/model-extractor-core.js";
import type { TypeSpecPropertyNode, TypeSpecTypeNode } from "../types/typespec-domain.js";

/**
 * Utility functions for model generation
 */
export class ModelGeneratorUtility {
  /**
   * Capitalize first letter of string
   */
  static capitalize(str: string): string {
    if (!str || typeof str !== 'string') {
      return str;
    }
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  /**
   * Convert camelCase to PascalCase
   */
  static toPascalCase(str: string): string {
    if (!str || typeof str !== 'string') {
      return str;
    }
    return str.replace(/(?:^|_)([a-z])/g, (_, char) => char.toUpperCase());
  }

  /**
   * Convert PascalCase to camelCase
   */
  static toCamelCase(str: string): string {
    if (!str || typeof str !== 'string') {
      return str;
    }
    return str.charAt(0).toLowerCase() + str.slice(1);
  }

  /**
   * Generate JSON tag for Go struct field
   */
  static getJsonTag(fieldName: string): string {
    return `json:"${fieldName}"`;
  }

  /**
   * Generate file name from model name
   */
  static getFileName(name: string): string {
    return `${name.toLowerCase()}.go`;
  }

  /**
   * Generate header comment for Go file
   */
  static generateHeader(modelName: string): string {
    return `// Auto-generated from TypeSpec model: ${modelName}
// Generated by Type-safe Professional Go Emitter`;
  }

  /**
   * Generate package declaration
   */
  static generatePackage(packageName: string = "api"): string {
    return `package ${packageName}`;
  }

  /**
   * Generate import statement
   */
  static generateImport(importPath: string, alias?: string): string {
    if (alias) {
      return `import ${alias} "${importPath}"`;
    }
    return `import "${importPath}"`;
  }

  /**
   * Generate imports block
   */
  static generateImports(imports: Set<string>): string {
    if (imports.size === 0) {
      return "";
    }

    const importStatements = Array.from(imports).map(imp => this.generateImport(imp));
    return `\n${importStatements.join('\n')}`;
  }

  /**
   * Generate struct body
   */
  static generateStructBody(modelName: string, fields: string[]): string {
    return `type ${modelName} struct {
${fields.join('\n')}
}`;
  }

  /**
   * Generate interface body
   */
  static generateInterfaceBody(interfaceName: string, methods: string[]): string {
    return `type ${interfaceName} interface {
${methods.join('\n')}
}`;
  }

  /**
   * Generate function body
   */
  static generateFunctionBody(
    functionName: string,
    parameters: string[],
    returnType: string,
    body: string[]
  ): string {
    const params = parameters.length > 0 ? parameters.join(", ") : "";
    const returnClause = returnType ? ` (${returnType})` : "";
    
    return `func ${functionName}(${params})${returnClause} {
${body.map(line => `  ${line}`).join('\n')}
}`;
  }

  /**
   * Generate footer comment
   */
  static generateFooter(): string {
    return `// End of generated file`;
  }

  /**
   * Generate complete Go file
   */
  static generateGoFile(
    modelName: string,
    packageDeclaration: string,
    header: string,
    imports: string,
    body: string,
    footer: string
  ): string {
    const sections = [packageDeclaration];
    
    if (header) {
      sections.push(header);
    }
    
    if (imports) {
      sections.push(imports);
    }
    
    sections.push(body);
    
    if (footer) {
      sections.push(footer);
    }
    
    return sections.join('\n\n');
  }

  /**
   * Generate HTTP handler function
   */
  static generateHttpHandler(
    operationName: string,
    httpVerb: string,
    httpPath: string,
    parameters: string[],
    returnType: string
  ): string {
    const functionName = `Handle${this.toPascalCase(operationName)}`;
    const params = ["w http.ResponseWriter", "r *http.Request", ...parameters];
    const body = [
      `// TODO: Implement ${httpVerb} ${httpPath} handler`,
      "// Extract and validate request parameters",
      "// Process business logic",
      "// Return response or error",
      "return nil, nil"
    ];
    
    return this.generateFunctionBody(functionName, params, returnType, body);
  }

  /**
   * Generate route registration function
   */
  static generateRouteRegistration(operations: ExtractedOperation[]): string {
    const routes: string[] = [];
    
    for (const operation of operations) {
      const handlerName = `Handle${this.toPascalCase(operation.name)}`;
      routes.push(`  mux.HandleFunc("${operation.path}", ${handlerName})`);
    }
    
    const functionName = "RegisterRoutes";
    const params = ["mux *http.ServeMux"];
    const body = [
      "// Register all HTTP routes",
      ...routes
    ];
    
    return this.generateFunctionBody(functionName, params, "", body);
  }

  /**
   * Generate service interface method
   */
  static generateServiceMethod(
    methodName: string,
    parameters: string[],
    returnType: string
  ): string {
    const params = parameters.join(", ");
    const fullReturnType = `${returnType}, error`;
    
    return `  ${methodName}(${params}) (${fullReturnType})`;
  }

  /**
   * Generate validation comment
   */
  static generateValidationComment(comment: string): string {
    return `// VALIDATION: ${comment}`;
  }

  /**
   * Generate TODO comment
   */
  static generateTodoComment(task: string): string {
    return `// TODO: ${task}`;
  }

  /**
   * Generate FIXME comment
   */
  static generateFixmeComment(issue: string): string {
    return `// FIXME: ${issue}`;
  }

  /**
   * Extract type name from TypeSpec type object
   */
  static extractTypeName(typeSpecType: TypeSpecTypeNode | TypeSpecPropertyNode | { kind?: string; name?: string }): string {
    if (!typeSpecType || typeof typeSpecType !== 'object') {
      return "interface{}";
    }
    
    switch (typeSpecType.kind) {
      case "scalar":
        return typeSpecType.name || "interface{}";
      case "model":
        return typeSpecType.name || "interface{}";
      case "union":
        return typeSpecType.name || "interface{}";
      case "template":
        return typeSpecType.name || "interface{}";
      case "Array":
        return `[]${this.extractTypeName(typeSpecType.elementType)}`;
      case "enum":
        return typeSpecType.name || "string";
      default:
        return "interface{}";
    }
  }

  /**
   * Check if type is optional
   */
  static isOptional(typeSpecType: TypeSpecTypeNode | TypeSpecPropertyNode | { optional?: boolean }): boolean {
    return typeSpecType && typeSpecType.optional === true;
  }

  /**
   * Generate Go doc comment
   */
  static generateGoDocComment(comment: string): string {
    const lines = comment.split('\n');
    const docLines = lines.map(line => `// ${line}`);
    return docLines.join('\n');
  }

  /**
   * Clean and normalize string for Go identifier
   */
  static cleanIdentifier(str: string): string {
    if (!str || typeof str !== 'string') {
      return "Unknown";
    }
    
    // Remove invalid characters and ensure it starts with a letter
    let cleaned = str.replace(/[^a-zA-Z0-9_]/g, '_');
    
    // Ensure it doesn't start with a number
    if (/^\d/.test(cleaned)) {
      cleaned = `_${cleaned}`;
    }
    
    // Ensure it's not a Go keyword
    const goKeywords = new Set([
      'break', 'case', 'chan', 'const', 'continue', 'default', 'defer', 'else',
      'fallthrough', 'for', 'func', 'go', 'goto', 'if', 'import', 'interface',
      'map', 'package', 'range', 'return', 'select', 'struct', 'switch', 'type', 'var'
    ]);
    
    if (goKeywords.has(cleaned)) {
      cleaned = `${cleaned}Field`;
    }
    
    return cleaned || "Unknown";
  }

  /**
   * Generate enum type for union variants
   */
  static generateEnumType(enumName: string, variants: string[]): string {
    const enumValues = variants.map(variant => `  ${variant} ${variant}Type`);
    
    return `type ${enumName} int

const (
${enumValues.join('\n')}
)

// String returns the string representation of ${enumName}
func (e ${enumName}) String() string {
  switch e {
${variants.map(variant => `  case ${variant}: return "${variant}"`).join('\n')}
  default: return "Unknown"
  }
}`;
  }

  /**
   * Generate error type for specific operations
   */
  static generateErrorType(errorName: string, errorFields: { name: string; type: string }[]): string {
    const fields = errorFields.map(field => `  ${field.name} ${field.type}`);
    
    return `type ${errorName} struct {
${fields.join('\n')}
}

// Error implements the error interface
func (e ${errorName}) Error() string {
  return fmt.Sprintf("${errorName}: %+v", *e)
}`;
  }
}