/**
 * Go Package Directory Component
 * Organizes Go files into proper package structure
 * Following guide's component composition pattern
 */

import type { Model } from "@typespec/compiler";
import { SourceDirectory, SourceFile } from "@alloy-js/core";
import { GoStructDeclaration } from "./GoStructDeclaration.js";

interface GoPackageDirectoryProps {
  /** Models to include in the package */
  models: Model[];
  /** Package name for the directory */
  packageName?: string;
  /** Additional documentation for the package */
  packageDocumentation?: string;
}

/**
 * Go Package Directory Component
 * Creates a complete Go package directory with:
 * - Proper package structure
 * - Multiple Go files
 * - Package documentation
 * - Model organization
 */
export function GoPackageDirectory({ 
  models, 
  packageName = "api",
  packageDocumentation
}: GoPackageDirectoryProps) {
  return (
    <SourceDirectory path={packageName}>
      {/* Package documentation file */}
      <SourceFile path="doc.go" filetype="go">
        {`// Package ${packageName} provides generated Go types
// 
// This package was automatically generated by TypeSpec Go Emitter
// DO NOT EDIT MANUALLY - regenerate from TypeSpec definitions

package ${packageName}

${packageDocumentation || ""}
`}
      </SourceFile>
      
      {/* Model files */}
      {models.map((model) => (
        <SourceFile 
          key={model.name}
          path={`${model.name.toLowerCase()}.go`} 
          filetype="go"
        >
          <GoStructDeclaration 
            model={model} 
            packageName={packageName}
          />
        </SourceFile>
      ))}
      
      {/* Package index file */}
      <SourceFile path="types.go" filetype="go">
        {`// Type declarations and exports for ${packageName} package
// This file provides convenient type exports and utilities

package ${packageName}

// Re-export all model types
${models.map(model => `// ${model.name} - TypeSpec model ${model.name}`).join('\n')}
`}
      </SourceFile>
    </SourceDirectory>
  );
}