/**
 * Go Struct Declaration Component
 * Professional Go struct generation with Alloy-JS
 * Following guide's component patterns and single responsibility principle
 */

import type { Model, ModelProperty } from "@typespec/compiler";
import { StructTypeDeclaration } from "@alloy-js/go";
import { refkey } from "@alloy-js/core";
import { GoFieldDeclaration } from "./GoFieldDeclaration.js";
import { GoImportManager } from "./GoImportManager.js";

interface GoStructDeclarationProps {
  /** TypeSpec model to convert to Go struct */
  model: Model;
  /** Optional struct documentation */
  documentation?: string;
  /** Package name for the struct */
  packageName?: string;
}

/**
 * Go Struct Declaration Component
 * Generates complete Go struct with proper field declarations, imports, and documentation
 * Follows guide's component composition pattern
 */
export function GoStructDeclaration({ 
  model, 
  documentation, 
  packageName = "api" 
}: GoStructDeclarationProps) {
  const modelRefkey = refkey(model);
  
  return (
    <>
      {/* Import management */}
      <GoImportManager model={model} packageName={packageName} />
      
      {/* Struct declaration with proper documentation */}
      <StructTypeDeclaration 
        name={model.name} 
        refkey={modelRefkey}
        documentation={documentation || `Code generated by TypeSpec Go Emitter\nSource: TypeSpec model: ${model.name}`}
      >
        {/* Generate struct fields for each property */}
        {Array.from(model.properties?.values() || []).map((prop: ModelProperty) => (
          <GoFieldDeclaration 
            key={prop.name}
            property={prop}
            modelRefkey={modelRefkey}
          />
        ))}
      </StructTypeDeclaration>
    </>
  );
}