package api

import "fmt"

// Code generated by TypeSpec Go Emitter
// Source: TypeSpec models

// Regular Models

type User struct {
  id int32 `json:"id"`
  name string `json:"name"`
  email string `json:"email,omitempty"` // optional
  age int32 `json:"age,omitempty"` // optional
}

