package api

import "fmt"

// Code generated by TypeSpec Go Emitter
// Source: TypeSpec models

// Regular Models

type User struct {
  id int32 `json:"id"`
  name string `json:"name"`
  email string `json:"email,omitempty"` // optional
  age int32 `json:"age,omitempty"` // optional
}

type Product struct {
  id int32 `json:"id"`
  title string `json:"title"`
  price float64 `json:"price"`
  description string `json:"description,omitempty"` // optional
}

