package api

// Code generated by TypeSpec Go Emitter
// Source: TypeSpec model: Product

import (
    "encoding/json"
    "time"
)

type Product struct {
    Id int32 `json:"id"`
    Title string `json:"title"`
    Price float64 `json:"price"`
    Description string `json:"description,omitempty"`
}
