package api

// Code generated by TypeSpec Go Emitter
// Source: TypeSpec model: User

import (
    "encoding/json"
    "time"
)

type User struct {
    Id int32 `json:"id"`
    Name string `json:"name"`
    Email string `json:"email,omitempty"`
    Age int32 `json:"age,omitempty"`
}
