import type { Program, EmitContext, Model, Type, ModelProperty } from "@typespec/compiler";
import { writeOutput } from "@typespec/emitter-framework";
import { Output } from "@alloy-js/core";
import * as go from "@alloy-js/go";

/**
 * Simple TypeSpec Go Emitter using Alloy-JS Framework
 * JSX syntax example - cleaner and more readable
 */
export async function $onEmit(context: EmitContext): Promise<void> {
  const models = extractModels(context.program);
  
  // Write output using AssetEmitter pattern
  writeOutput({
    [context.program.mainLibrary!.name]: renderGoModels(models),
  });
}

/**
 * Extract models from TypeSpec program
 */
function extractModels(program: Program): Model[] {
  const models: Model[] = [];
  for (const [name, namespace] of program.getGlobalNamespaceType().namespaces) {
    for (const [modelName, model] of namespace.models) {
      models.push(model);
    }
  }
  return models;
}

/**
 * Simple Go Emitter Output using Alloy-JS with JSX syntax
 * Recommended approach - cleaner and more maintainable
 */
function renderGoModels(models: Model[]) {
  return (
    <Output>
      <go.ModuleDirectory name="github.com/example/project">
        <go.SourceFile path="models.go" package="models">
          <go.ImportStatements>
            <go.SingleImportStatement path="fmt" />
          </go.ImportStatements>
          
          <go.LineComment>Code generated by Simple TypeSpec Go Emitter</go.LineComment>
          <go.LineComment>Source: TypeSpec models</go.LineComment>
          
          {models.map((model) => (
            <GoStructComponent key={model.name} model={model} />
          ))}
        </go.SourceFile>
      </go.ModuleDirectory>
    </Output>
  );
}

/**
 * Go struct component using JSX syntax
 * Component-based approach is cleaner
 */
function GoStructComponent({ model }: { model: Model }) {
  return (
    <>
      <go.LineComment>Generated from TypeSpec model: {model.name}</go.LineComment>
      <go.StructDeclaration name={model.name}>
        {Array.from(model.properties?.values() || []).map((prop: ModelProperty) => (
          <go.StructMember 
            key={prop.name}
            name={prop.name}
            type={mapTypeToGo(prop.type)}
            tag={{json: prop.name}}
          />
        ))}
      </go.StructDeclaration>
    </>
  );
}

/**
 * Simple type mapping using Alloy-JS
 * Working implementation without complexity
 */
function mapTypeToGo(type: Type): any {
  if (type.kind === "String") {
    return "string";
  }
  
  if (type.kind === "Boolean") {
    return "bool";
  }
  
  if (type.kind === "Number") {
    return "float64";
  }
  
  if (type.kind === "Int32") {
    return "int32";
  }
  
  if (type.kind === "Int64") {
    return "int64";
  }
  
  // Default fallback
  return "interface{}";
}