import type { Program, EmitContext, Model, Type, ModelProperty } from "@typespec/compiler";
import { writeOutput } from "@typespec/emitter-framework";
import { Output } from "@alloy-js/core";
import * as go from "@alloy-js/go";

/**
 * Simple TypeSpec Go Emitter using Alloy-JS Framework
 * JSX syntax example - cleaner and more readable
 */
export async function $onEmit(context: EmitContext): Promise<void> {
  const models = extractModels(context.program);
  
  // Write output using proper writeOutput API
  // TODO: FIX PROPER API USAGE - Need to determine correct output directory
  writeOutput(context.program, renderGoModels(models), "./generated");
}

/**
 * Extract models from TypeSpec program
 */
function extractModels(program: Program): Model[] {
  const models: Model[] = [];
  for (const [name, namespace] of program.getGlobalNamespaceType().namespaces) {
    for (const [modelName, model] of namespace.models) {
      models.push(model);
    }
  }
  return models;
}

/**
 * Simple Go Emitter Output using Alloy-JS with JSX syntax
 * Recommended approach - cleaner and more maintainable
 */
function renderGoModels(models: Model[]) {
  return (
    <Output>
      <go.ModuleDirectory name="github.com/example/project">
        <go.SourceFile path="models.go" package="models">
          <go.SingleImportStatement path="fmt" />
          
          <go.LineComment children="Code generated by Simple TypeSpec Go Emitter" />
          <go.LineComment children="Source: TypeSpec models" />
          
          {models.map((model) => (
            <>
              <GoStructComponent model={model} />
            </>
          ))}
        </go.SourceFile>
      </go.ModuleDirectory>
    </Output>
  );
}

/**
 * Go struct component using JSX syntax
 * Component-based approach is cleaner
 */
function GoStructComponent({ model }: { model: Model }) {
  return (
    <>
      <go.LineComment children={`Generated from TypeSpec model: ${model.name}`} />
      <go.StructTypeDeclaration name={model.name}>
        {Array.from(model.properties?.values() || []).map((prop: ModelProperty) => (
          <>
            <go.StructMember 
              name={prop.name}
              type={mapTypeToGo(prop.type)}
              tag={{json: prop.name}}
            />
          </>
        ))}
      </go.StructTypeDeclaration>
    </>
  );
}

/**
 * Maps TypeSpec types to Go type expressions for Alloy-JS
 * Returns simple string literals that Alloy.js Go components expect
 */
function mapTypeToGo(type: Type): any {
  // Handle intrinsic types (basic scalars)
  if (type.kind === "String") {
    return "string";
  }
  
  if (type.kind === "Boolean") {
    return "bool";
  }
  
  if (type.kind === "Number") {
    return "float64";
  }
  
  // Handle scalar types with proper scalar name checking
  if (type.kind === "Scalar" && (type as any).name) {
    const scalarName = (type as any).name;
    
    if (scalarName === "int32") {
      return "int32";
    }
    
    if (scalarName === "int64") {
      return "int64";
    }
    
    if (scalarName === "float32") {
      return "float32";
    }
    
    if (scalarName === "float64") {
      return "float64";
    }
    
    // Default scalar to string mapping
    return scalarName || "interface{}";
  }
  
  // Handle models
  if (type.kind === "Model") {
    return (type as any).name || "AnonymousModel";
  }
  
  // Default fallback
  return "interface{}";
}