import type { Program, EmitContext, Model, Type, ModelProperty } from "@typespec/compiler";
import { writeOutput } from "@typespec/emitter-framework";
import { Output, children } from "@alloy-js/core";
import * as go from "@alloy-js/go";
import { isNullType, isTemplateInstance, isStringType, isNumeric } from "@typespec/compiler";
import { isModelType, isScalarType, isUnionType } from "../types/typespec-type-guards.js";
import { Logger, LogContext } from "../domain/structured-logging.js";

/**
 * TypeSpec Go Emitter using Alloy-JS Framework
 * 
 * Professional implementation using Alloy components
 * Follows guide's reactive programming model and component patterns
 */
export async function $onEmit(context: EmitContext): Promise<void> {
  try {
    Logger.info(LogContext.TYPESPEC_INTEGRATION, "Starting TypeSpec Go Emitter with Alloy-JS");
    
    // Get all models from TypeSpec program
    const globalNamespace = context.program.getGlobalNamespaceType();
    const models = [...globalNamespace.models.values()];
    
    if (models.length === 0) {
      Logger.info(LogContext.TYPESPEC_INTEGRATION, "No models found in TypeSpec program");
      return;
    }
    
    Logger.info(
      LogContext.TYPESPEC_INTEGRATION, 
      `Found ${models.length} models to generate with Alloy-JS`,
      { modelNames: models.map(m => m.name || "unnamed") }
    );
    
    // Generate using Alloy-JS framework
    await writeOutput(
      context.program,
      <GoEmitterOutput program={context.program} models={models} />,
      context.emitterOutputDir,
    );
    
    Logger.info(LogContext.TYPESPEC_INTEGRATION, "TypeSpec Go Emitter with Alloy-JS completed successfully");
    
  } catch (error) {
    Logger.error(LogContext.TYPESPEC_INTEGRATION, "TypeSpec Go Emitter with Alloy-JS failed", { error });
    throw error;
  }
}

/**
 * Main TypeSpec Go Emitter Output Component using Alloy-JS
 * Generates Go files from TypeSpec program using professional Alloy components
 */
function GoEmitterOutput({ program, models }: { program: Program; models: Model[] }) {
  return (
    <Output>
      <go.ModuleDirectory name="github.com/example/project">
        <go.SourceDirectory path="models">
          <go.SourceFile path="models.go">
            <go.ImportStatements records={new Map()} />
            
            <go.LineComment children={"Code generated by TypeSpec Go Emitter with Alloy-JS"} />
            <go.LineComment children={"Source: TypeSpec models"} />
            
            {models.map((model, index) => children(() => (
              <GoModelStruct model={model} program={program} />
            ), { key: index }))}
          </go.SourceFile>
        </go.SourceDirectory>
      </go.ModuleDirectory>
    </Output>
  );
}

/**
 * Generate a Go struct from TypeSpec model using Alloy-JS Go components
 */
function GoModelStruct({ model, program }: { model: Model; program: Program }) {
  const structProps = Array.from(model.properties?.values() || []).map((prop: ModelProperty) => ({
    name: prop.name,
    type: mapTypeSpecToGoType(prop.type),
    tag: {json: prop.name, omitempty: prop.optional ? "true" : "false"}
  }));

  return (
      <children>
        <go.LineComment children={`Generated from TypeSpec model: ${model.name}`} />
        <go.StructTypeDeclaration name={model.name}>
          {structProps.map((props, index) => children(() => (
            <go.VariableDeclaration 
              name={props.name}
              type={props.type}
            />
          ), { key: index }))}
        </go.StructTypeDeclaration>
      </children>
  );
}

/**
 * Maps TypeSpec types to Go type expressions for Alloy-JS
 * Returns simple string literals that Alloy.js Go components expect
 */
function mapTypeSpecToGoType(type: Type): string {
  // Handle intrinsic types
  if (type.kind === "Intrinsic") {
    return "interface{}";
  }
  
  // Handle string types
  if (type.kind === "String") {
    return "string";
  }
  
  // Handle boolean types
  if (type.kind === "Boolean") {
    return "bool";
  }
  
  // Handle numeric types
  if (type.kind === "Number") {
    const numericMap: Record<string, string> = {
      "Int8": "int8",
      "Int16": "int16", 
      "Int32": "int32",
      "Int64": "int64",
      "Uint8": "uint8",
      "Uint16": "uint16",
      "Uint32": "uint32", 
      "Uint64": "uint64",
      "Float32": "float32",
      "Float64": "float64"
    };
    return numericMap[type.kind] || "int";
  }
  
  // Handle scalar types
  if (isScalarType(type)) {
    const scalarName = type.name?.toLowerCase() || "";
    const scalarMap: Record<string, string> = {
      "int8": "int8",
      "int16": "int16",
      "int32": "int32",
      "int64": "int64",
      "uint8": "uint8",
      "uint16": "uint16",
      "uint32": "uint32",
      "uint64": "uint64",
      "float32": "float32",
      "float64": "float64",
      "string": "string",
      "boolean": "bool",
      "bytes": "[]byte",
      "plaindate": "time.Time",
      "utcdatetime": "time.Time",
      "duration": "time.Duration",
    };
    return scalarMap[scalarName] || "interface{}";
  }
  
  // Handle model types
  if (isModelType(type)) {
    return type.name || "interface{}";
  }
  
  // Handle union types (optional types)
  if (isUnionType(type)) {
    const variants = Array.from(type.variants.values());
    if (variants.length === 2) {
      const hasNull = variants.some(v => isNullType(v.type));
      const nonNullVariant = variants.find(v => !isNullType(v.type));
      
      if (hasNull && nonNullVariant) {
        return "*" + mapTypeSpecToGoType(nonNullVariant.type);
      }
    }
    return "interface{}";
  }
  
  // Fallback
  return "interface{}";
}