import type { Program, EmitContext, Model } from "@typespec/compiler";
import { writeOutput } from "@typespec/emitter-framework";
import { StandaloneGoGenerator } from "../standalone-generator.js";
import { Logger, LogContext } from "../domain/structured-logging.js";
import {
  getModelName,
  hasErrorDecorator
} from "../types/typespec-type-guards.js";

/**
 * TypeSpec Go AssetEmitter - Simplified Working Implementation
 * 
 * Uses existing StandaloneGoGenerator with proper TypeSpec integration
 */
export async function $onEmit(context: EmitContext): Promise<void> {
  try {
    Logger.info(LogContext.TYPESPEC_INTEGRATION, "Starting TypeSpec Go AssetEmitter (simplified)");
    
    // Get all models from TypeSpec program
    const globalNamespace = context.program.getGlobalNamespaceType();
    const models = [...globalNamespace.models.values()];
    
    if (models.length === 0) {
      Logger.info(LogContext.TYPESPEC_INTEGRATION, "No models found in TypeSpec program");
      return;
    }
    
    Logger.info(
      LogContext.TYPESPEC_INTEGRATION, 
      `Found ${models.length} models to generate`,
      { modelNames: models.map(m => getModelName(m)) }
    );
    
    // Use existing StandaloneGoGenerator
    const generator = new StandaloneGoGenerator();
    let allGoCode = `package api

// Code generated by TypeSpec Go Emitter
// Source: TypeSpec models

`;
    
    // Generate Go code for each model
    for (const model of models) {
      const modelName = getModelName(model);
      Logger.info(LogContext.TYPESPEC_INTEGRATION, `Generating Go code for model: ${modelName}`);
      
      // Convert TypeSpec model to expected format
      const modelData = convertTypeSpecToGoModel(model, context.program);
      
      // Generate using existing logic
      const result = generator.generateModel(modelData);
      
      if (result._tag === "success") {
        const goCode = result.data.get("model.go") || "";
        allGoCode += goCode + "\n\n";
      } else {
        Logger.error(LogContext.TYPESPEC_INTEGRATION, `Failed to generate Go code for ${modelName}: ${(result as any).error?.message || result}`);
        allGoCode += `// Error generating ${modelName}: ${(result as any).error?.message || result}\n\n`;
      }
    }
    
    // Write output as simple text file (temporary approach)
    await writeOutput(context.program, allGoCode, context.emitterOutputDir || "./generated");
    
    Logger.info(LogContext.TYPESPEC_INTEGRATION, "TypeSpec Go AssetEmitter completed successfully");
    
  } catch (error) {
    Logger.error(LogContext.TYPESPEC_INTEGRATION, "TypeSpec Go AssetEmitter failed", { error });
    throw error;
  }
}

/**
 * Convert TypeSpec Model to StandaloneGoGenerator expected format
 */
function convertTypeSpecToGoModel(model: Model, program: Program): any {
  const properties = new Map();
  
  if (model.properties) {
    for (const [propName, prop] of model.properties) {
      properties.set(propName, {
        name: propName,
        type: prop.type,
        optional: prop.optional || false
      });
    }
  }

  return {
    name: getModelName(model),
    properties: properties,
    isErrorModel: hasErrorDecorator(program, model)
  };
}