/**
 * TypeSpec Go AssetEmitter - Minimal Working Implementation
 * Using exact TypeSpec v1.7.0 API patterns
 */

import type { EmitContext, Program, Model, ModelProperty, Type, Scalar } from "@typespec/compiler";
import { writeOutput } from "@typespec/emitter-framework";

// Minimal JSX implementation - avoid complex Alloy for now
interface GoFile {
  path: string;
  content: string;
}

interface GoStruct {
  name: string;
  fields: GoField[];
}

interface GoField {
  name: string;
  type: string;
  pointer: boolean;
  jsonTag: string;
}

/**
 * Main TypeSpec emitter entry point
 */
export async function $onEmit(context: EmitContext): Promise<void> {
  try {
    const program = context.program;
    const globalNamespace = program.getGlobalNamespaceType();
    const models = [...globalNamespace.models.values()];

    if (models.length === 0) {
      console.log("No models found in TypeSpec program");
      return;
    }

    console.log(`Generating Go code for ${models.length} models`);

    // Generate Go files using simple string concatenation
    const goFiles: GoFile[] = models.map((model) => ({
      path: `${model.name}.go`,
      content: generateGoFile(model),
    }));

    // Write files manually (simpler than JSX for now)
    await writeGoFiles(context, goFiles);

    console.log("✅ TypeSpec Go emission completed successfully");
  } catch (error) {
    console.error("❌ TypeSpec Go emission failed:", error);
    throw error;
  }
}

/**
 * Generate Go file content from TypeSpec model
 */
function generateGoFile(model: Model): string {
  const goStruct = convertModelToGoStruct(model);

  return `package api

// Code generated by TypeSpec Go Emitter
// Source: TypeSpec model: ${model.name}

import (
    "encoding/json"
    "time"
)

type ${goStruct.name} struct {
${goStruct.fields.map((field) => `    ${field.name} ${field.type} \`${field.jsonTag}\``).join("\n")}
}
`;
}

/**
 * Convert TypeSpec Model to Go Struct
 */
function convertModelToGoStruct(model: Model): GoStruct {
  return {
    name: model.name,
    fields: model.properties
      ? Array.from(model.properties.values()).map(convertPropertyToGoField)
      : [],
  };
}

/**
 * Convert TypeSpec Property to Go Field
 */
function convertPropertyToGoField(prop: ModelProperty): GoField {
  return {
    name: capitalize(prop.name),
    type: mapTypeSpecToGo(prop.type),
    pointer: prop.optional || false,
    jsonTag: prop.name + (prop.optional ? ",omitempty" : ""),
  };
}

/**
 * Map TypeSpec type to Go type
 */
function mapTypeSpecToGo(type: Type): string {
  switch (type.kind) {
    case "String":
      return "string";

    case "Boolean":
      return "bool";

    case "Scalar":
      const scalar = type as Scalar;
      switch (scalar.name) {
        case "int8":
          return "int8";
        case "int16":
          return "int16";
        case "int32":
          return "int32";
        case "int64":
          return "int64";
        case "uint8":
          return "uint8";
        case "uint16":
          return "uint16";
        case "uint32":
          return "uint32";
        case "uint64":
          return "uint64";
        case "float32":
          return "float32";
        case "float64":
          return "float64";
        case "bytes":
          return "[]byte";
        case "plainDate":
          return "time.Time";
        case "plainTime":
          return "time.Time";
        case "utcDateTime":
          return "time.Time";
        case "duration":
          return "time.Duration";
        default:
          return scalar.name;
      }

    case "Model":
      const model = type as Model;
      return model.name;

    default:
      console.warn(`Unsupported TypeSpec type: ${type.kind}`);
      return "interface{}";
  }
}

/**
 * Capitalize first letter for Go field names
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Simple file writer (replaces writeOutput for now)
 */
async function writeGoFiles(context: EmitContext, files: GoFile[]): Promise<void> {
  // For now, just output to console
  // Will integrate with writeOutput once basic types work
  files.forEach((file) => {
    console.log(`\n=== ${file.path} ===`);
    console.log(file.content);
  });
}
