import type { Program, EmitContext, Model, Type, Scalar } from "@typespec/compiler";
import { emitFile } from "@typespec/compiler";
import { Logger, LogContext } from "../domain/structured-logging.js";
import {
  isModelType,
  isScalarType,
  isUnionType,
  isEnumType,
  isArrayModel,
  getArrayElementType,
  getModelName,
  getScalarName,
  TypeSpecTypeSafeAccess
} from "../types/typespec-type-guards.js";

/**
 * TypeSpec Go AssetEmitter
 * 
 * Professional TypeSpec AssetEmitter implementation.
 * Integrates seamlessly with TypeSpec compiler ecosystem.
 */
export async function $onEmit(context: EmitContext): Promise<void> {
  try {
    Logger.info(LogContext.TYPESPEC_INTEGRATION, "Starting TypeSpec Go AssetEmitter");
    
    // Access models using TypeSpec v1.7.0 API
    const globalNamespace = context.program.getGlobalNamespaceType();
    const models = [...globalNamespace.models.values()];
    
    if (models.length === 0) {
      Logger.info(LogContext.TYPESPEC_INTEGRATION, "No models found in TypeSpec program");
      return;
    }
    
    Logger.info(
      LogContext.TYPESPEC_INTEGRATION, 
      `Found ${models.length} models to generate`,
      { modelNames: models.map(m => getModelName(m)) }
    );
    
    // Generate models.go with all model structs
    const modelsGoContent = await generateModelsGoFile(models, context);
    
    await emitFile(context.program, {
      path: context.emitterOutputDir ? `${context.emitterOutputDir}/models.go` : "models.go",
      content: modelsGoContent,
    });
    
    Logger.info(LogContext.TYPESPEC_INTEGRATION, "TypeSpec Go AssetEmitter completed successfully");
    
  } catch (error) {
    Logger.error(LogContext.TYPESPEC_INTEGRATION, "TypeSpec Go AssetEmitter failed", { error });
    throw error;
  }
}

/**
 * Generate models.go file content from TypeSpec models
 */
async function generateModelsGoFile(models: Model[], context: EmitContext): Promise<string> {
  const packageName = determinePackageName(context);
  let goContent = `package ${packageName}\n\n`;
  
  // Add file header
  goContent += `// Code generated by TypeSpec Go Emitter\n`;
  goContent += `// Source: TypeSpec models\n\n`;
  
  for (const model of models) {
    const modelCode = generateModelGoStruct(model);
    goContent += modelCode + "\n\n";
  }
  
  return goContent;
}

/**
 * Generate Go struct code for a single TypeSpec model
 */
function generateModelGoStruct(model: Model): string {
  const modelName = getModelName(model);
  let structCode = `type ${modelName} struct {\n`;
  
  const properties = model.properties || new Map();
  
  if (properties.size === 0) {
    structCode += `  // No properties defined\n`;
  } else {
    for (const [propName, prop] of properties) {
      const goType = mapTypeSpecToGo(prop.type);
      const jsonTag = prop.optional ? `${propName},omitempty` : propName;
      const optionalComment = prop.optional ? " // optional" : "";
      
      structCode += `  ${propName} ${goType} \`json:"${jsonTag}"\`${optionalComment}\n`;
    }
  }
  
  structCode += `}`;
  return structCode;
}

/**
 * Determine Go package name from context or default
 */
function determinePackageName(context: EmitContext): string {
  // TODO: Extract package name from TypeSpec configuration or namespace structure
  // For now, use default
  return "api";
}

function mapTypeSpecToGo(type: Type): string {
  // Use type guards instead of 'as any' casts
  if (isScalarType(type)) {
    return mapScalarToGo(type);
  }
  
  if (isModelType(type)) {
    return mapModelToGo(type);
  }
  
  if (isUnionType(type)) {
    return mapUnionToGo(type);
  }
  
  if (isEnumType(type)) {
    return mapEnumToGo(type);
  }
  
  // Handle builtin primitive types
  if (type.kind === "String") {
    return "string";
  }
  
  if (type.kind === "Boolean") {
    return "bool";
  }
  
  // Handle numeric types from test data
  const numericTypeMap: Record<string, string> = {
    "Int8": "int8",
    "Int16": "int16", 
    "Int32": "int32",
    "Int64": "int64",
    "Uint8": "uint8",
    "Uint16": "uint16",
    "Uint32": "uint32", 
    "Uint64": "uint64",
    "Float32": "float32",
    "Float64": "float64"
  };
  
  if (numericTypeMap[type.kind as string]) {
    return numericTypeMap[type.kind as string];
  }
  
  // Handle Array pattern from test data (Type = { kind: "Array", elementType: Type })
  if (type.kind === "Array" && (type as any).elementType) {
    const elementType = (type as any).elementType;
    const elementGoType = mapTypeSpecToGo(elementType);
    return `[]${elementGoType}`;
  }
  
  // Handle explicit scalar pattern from test data
  if (type.kind === "scalar" && (type as any).name) {
    const scalarName = ((type as any).name as string).toLowerCase();
    const scalarMap: Record<string, string> = {
      "string": "string",
      "boolean": "bool",
      "int8": "int8",
      "int16": "int16",
      "int32": "int32",
      "int64": "int64",
      "uint8": "uint8",
      "uint16": "uint16",
      "uint32": "uint32",
      "uint64": "uint64",
      "float32": "float32",
      "float64": "float64",
      "bytes": "[]byte",
      "plaindate": "string",
      "plaintime": "string",
      "utcdatetime": "time.Time",
      "offsetdatetime": "time.Time",
      "duration": "time.Duration",
      "url": "string",
      "null": "any"
    };
    return scalarMap[scalarName] || "any";
  }
  
  // Last resort: return any instead of interface{}
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    `Unhandled type kind: ${type.kind}, falling back to any`,
    { typeName: TypeSpecTypeSafeAccess.getTypeName(type) }
  );
  return "any";
}

function mapScalarToGo(scalar: Scalar): string {
  const scalarName = getScalarName(scalar).toLowerCase();
  
  // Map builtin scalars with type safety
  const scalarMap: Record<string, string> = {
    "string": "string",
    "boolean": "bool",
    "int8": "int8",
    "int16": "int16",
    "int32": "int32",
    "int64": "int64",
    "uint8": "uint8",
    "uint16": "uint16",
    "uint32": "uint32",
    "uint64": "uint64",
    "float32": "float32",
    "float64": "float64",
    "bytes": "[]byte",
    "plaindate": "string",
    "plaintime": "string",
    "utcdatetime": "time.Time",
    "offsetdatetime": "time.Time",
    "duration": "time.Duration",
    "url": "string",
    "null": "any"
  };
  
  const goType = scalarMap[scalarName];
  if (goType) {
    return goType;
  }
  
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    `Unknown scalar type: ${scalarName}, using any`,
    { scalarName }
  );
  return "any";
}

function mapModelToGo(model: Model): string {
  const modelName = getModelName(model);
  
  // Handle array models (TypeSpec creates Model for arrays)
  if (isArrayModel(model) && hasIndexer(model)) {
    const elementType = getArrayElementType(model);
    if (elementType) {
      const elementGoType = mapTypeSpecToGo(elementType);
      return `[]${elementGoType}`;
    }
  }
  
  // Regular model - return by name
  if (modelName && modelName !== "Array") {
    return modelName;
  }
  
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    `Model without name detected, using any`,
    { modelName }
  );
  return "any";
}

function mapUnionToGo(union: Type): string {
  // TODO: Implement proper union type handling
  // For now, use interface{} as Union placeholder
  // This will be replaced with sealed interface generation
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    "Union type handling not yet implemented, using interface{}",
    { unionName: TypeSpecTypeSafeAccess.getTypeName(union) }
  );
  return "interface{}";
}

function mapEnumToGo(enumType: Type): string {
  // TODO: Implement proper enum type handling
  // For now, use string as enum placeholder
  // This will be replaced with proper enum generation
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    "Enum type handling not yet implemented, using string",
    { enumName: TypeSpecTypeSafeAccess.getTypeName(enumType) }
  );
  return "string";
}

// Helper function to check indexer
function hasIndexer(model: Model): model is Model & { indexer: { value: Type } } {
  return !!model.indexer && "value" in model.indexer && !!model.indexer.value;
}