import type { Program, EmitContext, Model, Type, Scalar } from "@typespec/compiler";
import { emitFile } from "@typespec/compiler";
import { Logger, LogContext } from "../domain/structured-logging.js";
import {
  isModelType,
  isScalarType,
  isUnionType,
  isEnumType,
  isArrayModel,
  getArrayElementType,
  getModelName,
  getScalarName,
  hasErrorDecorator,
  TypeSpecTypeSafeAccess
} from "../types/typespec-type-guards.js";

/**
 * TypeSpec Go AssetEmitter
 * 
 * Professional TypeSpec AssetEmitter implementation.
 * Integrates seamlessly with TypeSpec compiler ecosystem.
 */
export async function $onEmit(context: EmitContext): Promise<void> {
  try {
    Logger.info(LogContext.TYPESPEC_INTEGRATION, "Starting TypeSpec Go AssetEmitter");
    
    // Access models using TypeSpec v1.7.0 API
    const globalNamespace = context.program.getGlobalNamespaceType();
    const models = [...globalNamespace.models.values()];
    
    if (models.length === 0) {
      Logger.info(LogContext.TYPESPEC_INTEGRATION, "No models found in TypeSpec program");
      return;
    }
    
    Logger.info(
      LogContext.TYPESPEC_INTEGRATION, 
      `Found ${models.length} models to generate`,
      { modelNames: models.map(m => getModelName(m)) }
    );
    
    // Generate models.go with all model structs
    const modelsGoContent = await generateModelsGoFile(models, context);
    
    await emitFile(context.program, {
      path: context.emitterOutputDir ? `${context.emitterOutputDir}/models.go` : "models.go",
      content: modelsGoContent,
    });
    
    Logger.info(LogContext.TYPESPEC_INTEGRATION, "TypeSpec Go AssetEmitter completed successfully");
    
  } catch (error) {
    Logger.error(LogContext.TYPESPEC_INTEGRATION, "TypeSpec Go AssetEmitter failed", { error });
    throw error;
  }
}

/**
 * Generate models.go file content from TypeSpec models
 */
async function generateModelsGoFile(models: Model[], context: EmitContext): Promise<string> {
  const packageName = determinePackageName(context);
  let goContent = `package ${packageName}\n\n`;
  
  // Add imports for error handling
  goContent += `import "fmt"\n\n`;
  
  // Add file header
  goContent += `// Code generated by TypeSpec Go Emitter\n`;
  goContent += `// Source: TypeSpec models\n\n`;
  
  // Separate regular models and error models
  const regularModels: Model[] = [];
  const errorModels: Model[] = [];
  
  for (const model of models) {
    if (hasErrorDecorator(context.program, model)) {
      errorModels.push(model);
    } else {
      regularModels.push(model);
    }
  }
  
  // Generate regular models first
  if (regularModels.length > 0) {
    goContent += `// Regular Models\n\n`;
    for (const model of regularModels) {
      const modelCode = generateModelGoStruct(model, context.program);
      goContent += modelCode + "\n\n";
    }
  }
  
  // Generate error models section with native Go error types
  if (errorModels.length > 0) {
    const errorPackageConfig = (context.options as any)["error-package"] as { enabled?: boolean; path?: string } | undefined;
    const errorPackageEnabled = errorPackageConfig?.enabled;
    const errorPackagePath = errorPackageConfig?.path || "pkg/errors";
    
    if (errorPackageEnabled) {
      // Generate centralized error package
      await generateErrorPackage(errorModels, errorPackagePath, context);
      goContent += `// Import centralized error package\n\n`;
      goContent += `import "${errorPackagePath}"\n\n`;
    } else {
      // Generate inline error models
      goContent += `// Error Models (generated from @error decorator)\n\n`;
      for (const model of errorModels) {
        const errorCode = generateGoError(model, context.program);
        goContent += errorCode + "\n\n";
      }
    }
  }
  
  return goContent;
}

/**
 * Generate Go struct code for a single TypeSpec model
 */
function generateModelGoStruct(model: Model, program: Program): string {
  const modelName = getModelName(model);
  const isError = hasErrorDecorator(program, model);
  
  // Add comment for error models
  const errorComment = isError ? `  // Error model generated from @error decorator\n` : "";
  
  let structCode = `type ${modelName} struct {\n`;
  
  const properties = model.properties || new Map();
  
  if (properties.size === 0) {
    structCode += `${errorComment}  // No properties defined\n`;
  } else {
    for (const [propName, prop] of properties) {
      // Ensure property type exists
      if (!prop || !prop.type) {
        Logger.warn(
          LogContext.TYPESPEC_INTEGRATION,
          `Property ${propName} has no type, skipping`
        );
        continue;
      }
      
      const goType = mapTypeSpecToGo(prop.type);
      const jsonTag = prop.optional ? `${propName},omitempty` : propName;
      const optionalComment = prop.optional ? " // optional" : "";
      
      structCode += `  ${propName} ${goType} \`json:"${jsonTag}"\`${optionalComment}\n`;
    }
  }
  
  structCode += `}`;
  return structCode;
}

/**
 * Generate Go native error code for @error decorated models
 */
function generateGoError(model: Model, program: Program): string {
  const modelName = getModelName(model);
  let errorCode = "";

  // Check if model has standard error properties
  const properties = model.properties || new Map();
  const hasCode = properties.has("code");
  const hasMessage = properties.has("message");
  const hasDetails = properties.has("details");

  // Generate error constructor function
  errorCode += `// New${modelName} creates a new ${modelName} error\n`;
  errorCode += `func New${modelName}(`;
  
  const constructorParams: string[] = [];
  
  if (hasCode) {
    constructorParams.push("code string");
  }
  if (hasMessage) {
    constructorParams.push("message string");
  }
  if (hasDetails) {
    constructorParams.push("details []string");
  }
  
  errorCode += constructorParams.join(", ");
  errorCode += `) *${modelName} {\n`;
  
  // Generate constructor body
  errorCode += `  return &${modelName}{\n`;
  
  if (hasCode) {
    errorCode += `    Code: code,\n`;
  }
  if (hasMessage) {
    errorCode += `    Message: message,\n`;
  }
  if (hasDetails) {
    errorCode += `    Details: details,\n`;
  }
  
  errorCode += `  }\n`;
  errorCode += `}\n\n`;

  // Generate error method to implement error interface
  errorCode += `// Error implements the built-in error interface\n`;
  errorCode += `func (e *${modelName}) Error() string {\n`;
  errorCode += `  if e == nil {\n`;
  errorCode += `    return "${modelName}: nil"\n`;
  errorCode += `  }\n\n`;
  
  if (hasCode && hasMessage) {
    errorCode += `  return fmt.Sprintf("${modelName}[code=%s, message=%s]", e.Code, e.Message)\n`;
  } else if (hasCode) {
    errorCode += `  return fmt.Sprintf("${modelName}[code=%s]", e.Code)\n`;
  } else {
    errorCode += `  return fmt.Sprintf("${modelName}[%s]", e.Message)\n`;
  }
  
  errorCode += `}\n\n`;
  
  // Generate error type definition
  errorCode += `// ${modelName} represents a TypeSpec @error model\n`;
  errorCode += `type ${modelName} struct {\n`;
  
  for (const [propName, prop] of properties) {
    const goType = mapTypeSpecToGo(prop.type);
    const jsonTag = prop.optional ? `${propName},omitempty` : propName;
    
    errorCode += `  ${propName} ${goType} \`json:"${jsonTag}"\`\n`;
  }
  
  errorCode += `}\n\n`;

  return errorCode;
}

/**
 * Determine Go package name from context or default
 */
function determinePackageName(context: EmitContext): string {
  // TODO: Extract package name from TypeSpec configuration or namespace structure
  // For now, use default
  return "api";
}

function mapTypeSpecToGo(type: Type): string {
  // Use type guards instead of 'as any' casts
  if (isScalarType(type)) {
    return mapScalarToGo(type);
  }
  
  if (isModelType(type)) {
    return mapModelToGo(type);
  }
  
  if (isUnionType(type)) {
    return mapUnionToGo(type);
  }
  
  if (isEnumType(type)) {
    return mapEnumToGo(type);
  }
  
  // Handle builtin primitive types
  if (type.kind === "String") {
    return "string";
  }
  
  if (type.kind === "Boolean") {
    return "bool";
  }
  
  // Handle numeric types from test data
  const numericTypeMap: Record<string, string> = {
    "Int8": "int8",
    "Int16": "int16", 
    "Int32": "int32",
    "Int64": "int64",
    "Uint8": "uint8",
    "Uint16": "uint16",
    "Uint32": "uint32", 
    "Uint64": "uint64",
    "Float32": "float32",
    "Float64": "float64"
  };
  
  const kind = type.kind;
  if (numericTypeMap[kind]) {
    return numericTypeMap[kind];
  }
  
  // Handle Array pattern using TypeSpec compiler types
  if (isModelType(type) && isArrayModel(type)) {
    const elementType = getArrayElementType(type);
    if (elementType) {
      const elementGoType = mapTypeSpecToGo(elementType);
      return `[]${elementGoType}`;
    }
  }
  
  // Handle scalar types properly
  if (isScalarType(type)) {
    return mapScalarToGo(type);
  }
  
  // Last resort: return any instead of interface{}
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    `Unhandled type kind: ${type.kind}, falling back to any`,
    { typeName: TypeSpecTypeSafeAccess.getTypeName(type) }
  );
  return "any";
}

function mapScalarToGo(scalar: Scalar): string {
  const scalarName = getScalarName(scalar).toLowerCase();
  
  // Map builtin scalars with type safety
  const scalarMap: Record<string, string> = {
    "string": "string",
    "boolean": "bool",
    "int8": "int8",
    "int16": "int16",
    "int32": "int32",
    "int64": "int64",
    "uint8": "uint8",
    "uint16": "uint16",
    "uint32": "uint32",
    "uint64": "uint64",
    "float32": "float32",
    "float64": "float64",
    "bytes": "[]byte",
    "plaindate": "string",
    "plaintime": "string",
    "utcdatetime": "time.Time",
    "offsetdatetime": "time.Time",
    "duration": "time.Duration",
    "url": "string",
    "null": "any"
  };
  
  const goType = scalarMap[scalarName];
  if (goType) {
    return goType;
  }
  
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    `Unknown scalar type: ${scalarName}, using any`,
    { scalarName }
  );
  return "any";
}

function mapModelToGo(model: Model): string {
  const modelName = getModelName(model);
  
  // Handle array models (TypeSpec creates Model for arrays)
  if (isArrayModel(model) && hasIndexer(model)) {
    const elementType = getArrayElementType(model);
    if (elementType) {
      const elementGoType = mapTypeSpecToGo(elementType);
      return `[]${elementGoType}`;
    }
  }
  
  // Regular model - return by name
  if (modelName && modelName !== "Array") {
    return modelName;
  }
  
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    `Model without name detected, using any`,
    { modelName }
  );
  return "any";
}

function mapUnionToGo(union: Type): string {
  // TODO: Implement proper union type handling
  // For now, use interface{} as Union placeholder
  // This will be replaced with sealed interface generation
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    "Union type handling not yet implemented, using interface{}",
    { unionName: TypeSpecTypeSafeAccess.getTypeName(union) }
  );
  return "interface{}";
}

function mapEnumToGo(enumType: Type): string {
  // TODO: Implement proper enum type handling
  // For now, use string as enum placeholder
  // This will be replaced with proper enum generation
  Logger.warn(
    LogContext.TYPESPEC_INTEGRATION,
    "Enum type handling not yet implemented, using string",
    { enumName: TypeSpecTypeSafeAccess.getTypeName(enumType) }
  );
  return "string";
}

// Helper function to check indexer
function hasIndexer(model: Model): model is Model & { indexer: { value: Type } } {
  return !!model.indexer && "value" in model.indexer && !!model.indexer.value;
}

/**
 * Generate centralized error package
 * 
 * Creates a separate package for all error types with proper Go package structure.
 */
async function generateErrorPackage(
  errorModels: Model[], 
  packagePath: string, 
  context: EmitContext
): Promise<void> {
  let packageContent = `// Package errors provides centralized error types from TypeSpec @error models
// This package is auto-generated. Do not modify manually.

package errors

import "fmt"
`;

  // Generate all error types in the centralized package
  for (const model of errorModels) {
    const errorCode = generateGoError(model, context.program);
    packageContent += errorCode + "\n\n";
  }

  // Write the error package file
  const packageFile = `${packagePath}/errors.go`;
  await emitFile(context.program, {
    path: context.emitterOutputDir ? `${context.emitterOutputDir}/${packageFile}` : packageFile,
    content: packageContent,
  });
  
  Logger.info(
    LogContext.TYPESPEC_INTEGRATION,
    `Generated centralized error package: ${packageFile}`
  );
}