import type { Program, EmitContext, Model, Type, ModelProperty } from "@typespec/compiler";
import { writeOutput } from "@typespec/emitter-framework";
import { Output } from "@alloy-js/core";
import * as go from "@alloy-js/go";

/**
 * Simple TypeSpec Go Emitter using Alloy-JS Framework
 * Following guide exactly - no complexity, just working code
 */
export async function $onEmit(context: EmitContext): Promise<void> {
  try {
    console.log("🚀 Starting simple TypeSpec Go Emitter with Alloy-JS");
    
    // Get all models from TypeSpec program
    const globalNamespace = context.program.getGlobalNamespaceType();
    const models = [...globalNamespace.models.values()];
    
    if (models.length === 0) {
      console.log("ℹ️ No models found in TypeSpec program");
      return;
    }
    
    console.log(`✅ Found ${models.length} models to generate`);
    
    // Generate using Alloy-JS framework
    await writeOutput(
      context.program,
      <SimpleGoEmitterOutput models={models} />,
      context.emitterOutputDir,
    );
    
    console.log("✅ Simple TypeSpec Go Emitter completed successfully");
    
  } catch (error) {
    console.error("❌ Simple TypeSpec Go Emitter failed:", error);
    throw error;
  }
}

/**
 * Simple Go Emitter Output using Alloy-JS
 * Following guide exactly - minimal working implementation
 */
function SimpleGoEmitterOutput({ models }: { models: Model[] }) {
  return (
    <Output>
      <go.ModuleDirectory name="github.com/example/project">
        <go.SourceFile path="models.go" package="models">
          <go.ImportStatement>fmt</go.ImportStatement>
          
          <go.Comment>Code generated by Simple TypeSpec Go Emitter</go.Comment>
          <go.Comment>Source: TypeSpec models</go.Comment>
          
          {models.map((model) => (
            <SimpleGoStruct key={model.name} model={model} />
          ))}
        </go.SourceFile>
      </go.ModuleDirectory>
    </Output>
  );
}

/**
 * Simple Go struct generation using Alloy-JS
 * Minimal working implementation
 */
function SimpleGoStruct({ model }: { model: Model }) {
  return (
    <>
      <go.Comment>Generated from TypeSpec model: {model.name}</go.Comment>
      <go.StructDeclaration name={model.name}>
        {Array.from(model.properties?.values() || []).map((prop: ModelProperty) => (
          <go.StructMember 
            key={prop.name}
            name={prop.name}
            type={mapTypeToGo(prop.type)}
            tag={{json: prop.name}}
          />
        ))}
      </go.StructDeclaration>
    </>
  );
}

/**
 * Simple type mapping using Alloy-JS
 * Working implementation without complexity
 */
function mapTypeToGo(type: Type): any {
  if (type.kind === "String") {
    return "string";
  }
  
  if (type.kind === "Boolean") {
    return "bool";
  }
  
  if (type.kind === "Number") {
    return "int64";
  }
  
  // Default to interface for unknown types
  return "interface{}";
}