import { Output } from "@alloy-js/core";
import { ModuleDirectory, SourceDirectory, SourceFile } from "@alloy-js/go";
import type { EmitContext, Namespace, Model, ModelProperty } from "@typespec/compiler";
import { writeOutput } from "@typespec/emitter-framework";

function toPascalCase(str: string): string {
	return str.replace(/(?:^|[_-])(\w)/g, (_, c) => c.toUpperCase());
}

function mapTypeSpecTypeToGo(prop: ModelProperty): string {
	// Handle scalar types (like string, int32, etc.)
	if (prop.type.kind === "Scalar" && prop.type.name) {
		const typeMap: Record<string, string> = {
			"string": "string",
			"boolean": "bool", 
			"int8": "int8",
			"int16": "int16", 
			"int32": "int32",
			"int64": "int64",
			"uint8": "uint8",
			"uint16": "uint16",
			"uint32": "uint32", 
			"uint64": "uint64",
			"float32": "float32",
			"float64": "float64",
			"bytes": "[]byte",
			"plainDate": "string",
			"plainTime": "string", 
			"utcDateTime": "time.Time",
			"offsetDateTime": "time.Time",
			"duration": "time.Duration",
			"url": "string",
		};
		return typeMap[prop.type.name] || "any";
	}
	
	// Handle model types
	if (prop.type.kind === "Model") {
		return toPascalCase(prop.type.name);
	}
	
	// Default fallback
	return "any";
}

function generateProperty(prop: ModelProperty): string {
	const propName = toPascalCase(prop.name);
	const goType = mapTypeSpecTypeToGo(prop);
	const jsonTag = prop.name;
	
	return `\t${propName} ${goType} \`json:"${jsonTag}"\``;
}

function generateModel(model: Model): string {
	const modelName = toPascalCase(model.name);
	const properties: string[] = [];
	
	// Access properties properly using forEach
	model.properties.forEach((prop, key) => {
		properties.push(generateProperty(prop));
	});
	
	const propertiesStr = properties.join("\n");
	
	return `type ${modelName} struct {
${propertiesStr}
}`;
}

export async function $onEmit(context: EmitContext) {
	const mainNamespace = context.program.getGlobalNamespaceType();
	
	await writeOutput(
		context.program,
		<Output>
			<ModuleDirectory name="example.com/output">
				<SourceDirectory path="api">
					<SourceFile path="models.go">{`package api

// Generated by TypeSpec Go Emitter
${generateModelsFromNamespace(mainNamespace)}
`}</SourceFile>
				</SourceDirectory>
			</ModuleDirectory>
		</Output>,
		context.emitterOutputDir,
	);
}

function generateModelsFromNamespace(namespace: Namespace): string {
	const models: Model[] = [];
	
	// Find all models in namespace
	for (const model of namespace.models.values()) {
		models.push(model);
	}
	
	return models.map(model => generateModel(model)).join("\n\n");
}